#! /bin/sh
# /etc/init.d/BlinkyTapeTestRig

### BEGIN INIT INFO
# Provides:          BlinkyTapeTestRig
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting test rig"
    # run application you want to start
    bash -c 'cd /home/pi/BlinkyTape/TestProgram_Beaglebone/; ./run_testrig.sh'
    ;;
  stop)
    echo "Stopping test rig"
    # kill application you want to stop
    killall BlinkyTapeTestRig 
    ;;
  *)
    echo "Usage: /etc/init.d/BlinkyTapeTestRig {start|stop}"
    exit 1
    ;;
esac

exit 0
